# Generated by Django 3.0.5 on 2020-11-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=150)),
                ('test_result', models.CharField(max_length=150)),
                ('ttn_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_ttn', to='app.TTN')),
            ],
        ),
    ]
